import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {setRequestLocale} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import "./globals.css";
import Header from '@/app/[locale]/components/Header'
import Footer from "@/app/[locale]/components/Footer";
import CookiesModal from "@/app/[locale]/components/CookiesModal";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export function generateStaticParams(){
  return routing.locales.map((locale)=>({locale}))
}

export const metadata = {
  title: "Gilian IT-Dienst",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const {locale} = await params;
  if (!routing.locales.includes( locale)) {
    notFound();
  }
  setRequestLocale(locale);
  
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={` antialiased flex flex-col justify-between h-screen`}
      >
        <NextIntlClientProvider messages={messages}>

          <Header home={messages.Header.Home} about={messages.Header.About} blog={messages.Header.Blog} careers={messages.Header.Careers} contact={messages.Header.Contact}  />
          {children}
          <Footer terms={messages.Footer.terms} privacy={messages.Footer.privacy}/>
          <CookiesModal title={messages.Cookies.h2} p={messages.Cookies.p} btn1={messages.Cookies.btn1} btn2={messages.Cookies.btn2}/>

        </NextIntlClientProvider>
      </body>
    </html>
  );
}
