import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import "./globals.css";
import Header from '@/app/[locale]/components/Header'
import Footer from "@/app/[locale]/components/Footer";
import CookiesModal from "@/app/[locale]/components/CookiesModal";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const {locale} = await params;
  if (!routing.locales.includes( locale)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={` antialiased flex flex-col justify-between h-screen`}
      >
        <NextIntlClientProvider messages={messages}>

          <Header/>
          {children}
          <Footer/>
          <CookiesModal/>

        </NextIntlClientProvider>
      </body>
    </html>
  );
}
